name: Deploy Jekyll with GitHub Pages dependencies preinstalled
on:
  push:
    branches:
      - master
permissions:
  contents: write
jobs:
  build-and-deploy: 
   runs-on: ubuntu-latest 
   steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run:  npm i && npm run build
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        folder: dist
        branch: hg-pages
